### ISSUE TITLE
Meta Audience Network

### ISSUE THREAD

**Issue by cristianpessoamillenium** [nooralibutt/easy-ads#106]
Audience network ads don't work

**Comment by nooralibutt** [comment]
@cristianpessoamillenium what issue are you facing?

**Comment by huzaibsayyed** [comment]
@nooralibutt FB ads are not showing, at all. I want admob and facebook, but fb ads are not showing, not 

`flutter: \^[[38;5;196m┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────<…>
flutter: \^[[38;5;196m│ #0   EasyLogger._onAdFailedToLoad (package:easy_ads_flutter/src/utils/easy_logger.dart:43:13)<…>
flutter: \^[[38;5;196m│ #1   EasyLogger._onAdEvent (package:easy_ads_flutter/src/utils/easy_logger.dart:83:9)<…>
flutter: \^[[38;5;196m├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄<…>
flutter: \^[[38;5;196m│ ⛔ banner ads for facebook could not be loaded.<…>
flutter: \^[[38;5;196m│ ⛔ ERROR: Error occurred while loading null null ad<…>
flutter: \^[[38;5;196m└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────<…>
`

`
EasySmartBannerAd(
            priorityAdNetworks: [
              AdNetwork.facebook,
              // AdNetwork.admob,
            ],
            adSize: AdSize.largeBanner,
          ),
`

**Comment by huzaibsayyed** [comment]
```
flutter: \^[[38;5;12m┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────<…>
flutter: \^[[38;5;12m│ #0   EasyLogger.logInfo (package:easy_ads_flutter/src/utils/easy_logger.dart:19:43)<…>
flutter: \^[[38;5;12m│ #1   EasyAds.showAd (package:easy_ads_flutter/src/easy_ads.dart:401:17)<…>
flutter: \^[[38;5;12m├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄<…>
flutter: \^[[38;5;12m│ 💡 AdNetwork.facebook AdUnitType.interstitial was not loaded, so called loading<…>
flutter: \^[[38;5;12m└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────<…>
flutter: \^[[38;5;196m┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────<…>
flutter: \^[[38;5;196m│ #0   EasyLogger._onAdFailedToLoad (package:easy_ads_flutter/src/utils/easy_logger.dart:43:13)<…>
flutter: \^[[38;5;196m│ #1   EasyLogger._onAdEvent (package:easy_ads_flutter/src/utils/easy_logger.dart:83:9)<…>
flutter: \^[[38;5;196m├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄<…>
flutter: \^[[38;5;196m│ ⛔ interstitial ads for facebook could not be loaded.<…>
flutter: \^[[38;5;196m│ ⛔ ERROR: Error occurred while loading 1001 No fill ad<…>
flutter: \^[[38;5;196m└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────<…>

```


```
EasyAds.instance.showAd(adNetwork: AdNetwork.facebook, AdUnitType.interstitial);
```

**Comment by nooralibutt** [comment]
Somehow facebook ads don't work at all for some apps. I still haven't figured out what are the settings we need to do to make it work.
