### ISSUE TITLE
Weird Error !!! FAILED BINDER TRANSACTION !!! 

### ISSUE THREAD

**Issue by turbobuilt** [nooralibutt/easy-ads#81]
I'm using only facebook ads, get the weird error below.  Not sure what's up.  Not I did include the google admob id in the android xml config file because it crashed when that wasn't there.  The facebook ads still show though.

Android emulator api 33

[✓] Flutter (Channel stable, 3.10.6, on macOS 13.3 22E252 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.83.1)
[✓] Connected device (5 available)

E/JavaBinder(15185): !!! FAILED BINDER TRANSACTION !!!  (parcel size = 156)
I/AdvertisingIdClient(15185): GMS remote exception 
I/AdvertisingIdClient(15185): android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died, but this could also be caused by running out of binder buffe
I/AdvertisingIdClient(15185):   at android.os.BinderProxy.transactNative(Native Method)
I/AdvertisingIdClient(15185):   at android.os.BinderProxy.transact(BinderProxy.java:584)
I/AdvertisingIdClient(15185):   at com.google.android.gms.internal.ads_identifier.zza.zzb(com.google.android.gms:play-services-ads-identifier@@17.1.0:2)
I/AdvertisingIdClient(15185):   at com.google.android.gms.internal.ads_identifier.zzd.zzc(com.google.android.gms:play-services-ads-identifier@@17.1.0:2)
I/AdvertisingIdClient(15185):   at com.google.android.gms.ads.identifier.AdvertisingIdClient.zzd(com.google.android.gms:play-services-ads-identifier@@17.1.0:9)
I/AdvertisingIdClient(15185):   at com.google.android.gms.ads.identifier.AdvertisingIdClient.getAdvertisingIdInfo(com.google.android.gms:play-services-ads-identifier@@17.1.0:4)
I/AdvertisingIdClient(15185):   at java.lang.reflect.Method.invoke(Native Method)
I/AdvertisingIdClient(15185):   at com.facebook.ads.redexgen.X.5z.A00(:14722)
I/AdvertisingIdClient(15185):   at com.facebook.ads.redexgen.X.5y.A02(:14689)
I/AdvertisingIdClient(15185):   at com.facebook.ads.redexgen.X.5y.A00(:14667)
I/AdvertisingIdClient(15185):   at com.facebook.ads.redexgen.X.5s.A01(:14562)
I/AdvertisingIdClient(15185):   at com.facebook.ads.redexgen.X.5s.A07(:14603)
I/AdvertisingIdClient(15185):   at com.facebook.ads.redexgen.X.So.A06(:53111)
I/AdvertisingIdClient(15185):   at com.facebook.ads.redexgen.X.Ju.run(:40743)
I/AdvertisingIdClient(15185):   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
I/AdvertisingIdClient(15185):   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
I/AdvertisingIdClient(15185):   at java.lang.Thread.run(Thread.java:1012)
E/JavaBinder(15185): !!! FAILED BINDER TRANSACTION !!!  (parcel size = 156)

**Comment by turbobuilt** [comment]
Ok this happened for some weird reason because of the emulator.  Did a cold reboot of emulator and it went away.
