### ISSUE TITLE
facebook and Google both ads are not load and show when ad id is real.

### ISSUE THREAD

**Issue by vocsygautam** [nooralibutt/easy-ads#94]
#0   EasyLogger._onAdFailedToLoad (package:easy_ads_flutter/src/utils/easy_logger.dart:43:13)<…>
#1   EasyLogger._onAdEvent (package:easy_ads_flutter/src/utils/easy_logger.dart:83:9)<…>
banner ads for facebook could not be loaded.<…>
ERROR: Error occurred while loading 1001 No fill ad<…>

banner ads for admob could not be loaded.<…>
ERROR: LoadAdError(code: 1, domain: com.google.admob, message: Request Error: No ad to show., responseInfo: ResponseInfo(responseId: null, mediationAdapterClassName: null, adapterResponses: [], loadedAdapterResponseInfo: AdapterResponseInfo(adapterClassName: , latencyMillis: 0, description: , adUnitMapping: {}, adError: null, adSourceName: , adSourceId: , adSourceInstanceName: , adSourceInstanceId: )), responseExtras: {})<…>

**Comment by nooralibutt** [comment]
This is not a package issue, clearly you can see from logs that there is no ad fill
